import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      index: true,
    },

    description: {
      type: String,
    },

    advanced: {
      type: Number,
      default: 0,
    },

    salary: {
      type: Number,
      required: true,
    },

    overTime: {
      type: Number,
      default: 0,
    },

    designation: {
      type: String,
      enum: ["mazdoor", "qarigar"],
      // required: true,
    },

    // salaryType: {
    //   type: String,
    //   enum: ["daily", "weekly", "monthly", "contract"],
    //   default: "daily",
    // },

    workUnder: {
      type: String,
      enum: ["owner", "partnerShip", "client"],
      required: true,
      // index: true,
    },

    currentSite: {
      type: String,
    },

    workStatus: {
      type: String,
      enum: ["pending", "inprogress", "complete"],
      default: "pending",
    },

    attendence: {
      type: String,
      enum: ["present", "absent"],
      default: "absent",
    },

    entryDate: {
      type: Date,
      default: Date.now
    },

    // teamName: {
    //   type: String,
    //   default: "owner",
    // },

    deleted_at: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: {
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
);

const User = mongoose.model("Employer", userSchema);
export default User;

//   {
//     id: 1,
//     projectSummary: "Web Inventix LLC provided mobile app development services for an e-commerce solutions company. Their deliverables included UI/UX design, QA testing, front- and backend development, and post-launch support.",
//     projectService: "Mobile App Development",
//     prjectSize: "$10,000 to $49,999",
//     projectLenght: "Mar. - June 2024",
//     name: "Becky Erin",
//     role: "CTO, InnovaCore",
//     location: "Northeast - USA",
//     employees: "51-200 Employees",
//     review:
//       "Their attention to detail, combined with strong technical expertise and creativity, made the process smooth.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/327428",
//   },
//   {
//     id: 2,
//     projectSummary: "Web Inventix developed a law firm management system for a legal technology firm. They integrated features, including AI-driven legal document automation, real-time case tracking, and cloud-based data storage.",
//     projectService: "Custom Software Development",
//     prjectSize: "Project size Less than $10,000",
//     projectLenght: "Dec. 2024 - Mar. 2025",
//     name: "Cassie Watts",
//     role: "Director, Legal Tech Company",
//     location: "Acton, California",
//     employees: "11-50 Employees",
//     review:
//       "Their commitment to quality and innovation made the project a success.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/360395",

//   },
//   {
//     id: 3,
//     projectSummary: "Web Inventix developed a vendor construction app for a construction solutions company. The team designed the UI/UX and integrated features, including real-time tracking, AI analytics, and secure payments.",
//     projectService: "Mobile App Development",
//     prjectSize: "Project size Less than $10,000",
//     projectLenght: "Jan. - Mar. 2025",
//     name: "Corey Farina",
//     role: "Owner, Construction Company",
//     location: "San Jose, California",
//     employees: "11-50 Employees",
//     review: "Web Inventix impressed us with their advanced technology.",
//     rating: 4.5,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/359795",

//   },
//   {
//     id: 4,
//     projectSummary: "Web Inventix developed a mobile app for an IT company. They translated the provided Figma designs into code and integrated APIs.",
//     projectService: "API Development Mobile App Development",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Nov. 2024 - Feb. 2025",
//     name: "Stephen McBride",
//     role: "Co-Founder & CEO, IT Company",
//     location: "Bartlett, Illinois",
//     employees: "11-50 Employees",
//     review:
//       "They were always helpful and thorough, making the entire process smooth and enjoyable at every stage.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/359140",

//   },
//   {
//     id: 5,
//     projectSummary: "Web Inventix LLC provided digital marketing services for an accounting firm. Their work included content creation, ad campaign management, audience targeting, performance tracking, and monthly reports.",
//     projectService: "Search Engine Optimization Social Media Marketing",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Oct. 2024 - Jan. 2025",
//     name: "Smith Paul",
//     role: "CMO, Accounting Firm",
//     location: "Dallas, Texas",
//     employees: "11-50 Employees",
//     review:
//       "Their data-driven approach and attention to detail in audience segmentation set them apart.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/343980",

//   },
//   {
//     id: 6,
//     projectSummary: "Web Inventix LLC provided social media marketing services for a mobile app development company. The team created content and ran campaigns on Facebook, LinkedIn, and X with the goal of generating leads.",
//     projectService: "Social Media Marketing",
//     prjectSize: "Less than $10,000",
//     projectLenght: "June 2024 - Jan. 2025",
//     name: "Paulet Dao",
//     role: "Support Manager, Mobile App Development Company",
//     location: "Sheridan, Wyoming",
//     employees: "11-50 Employees",
//     review:
//       "Their creativity, data-driven decisions, and ability to adapt quickly to changes made a significant impact.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/342756",

//   },
//   {
//     id: 7,
//     projectSummary: "Web Inventix LLC developed an e-commerce platform for an HR company. They integrated the client's existing systems into the site and provided post-launch support.",
//     projectService: "E-Commerce Development",
//     prjectSize: "$10,000 to $49,999",
//     projectLenght: "Aug. 2023 - Feb. 2024",
//     name: "Billie Morrow",
//     role: "Associate Manager, HR Company",
//     location: "Chicago, Illinois",
//     employees: "11-50 Employees",
//     review: "They promptly addressed our needs.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/342749",

//   },
//   {
//     id: 8,
//     projectSummary: "Web Inventix LLC developed a digital marketing agency's iOS and Android app using Flutter. The team designed the app's UI, integrated customer engagement features, automated processes, and conducted tests.",
//     projectService: "Mobile App Development UX/UI Design",
//     prjectSize: "$10,000 to $49,999",
//     projectLenght: "Mar. - Dec. 2022",
//     name: "Kayla Henderson",
//     role: "Executive Director, Digital Marketing Agency",
//     location: "Dallas, Texas",
//     employees: "11-50 Employees",
//     review:
//       "They remained proactive in offering solutions to enhance the app’s functionality and UX.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/341981",

//   },
//   {
//     id: 9,
//     projectSummary: "Web Inventix LLC developed a React Native app for a digital marketing company. The team was responsible for requirements analysis, UI/UX design, backend integration, testing, deployment, and support.",
//     projectService: "Mobile App Development UX/UI Design",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Jan. - Oct. 2024",
//     name: "Vanessa Oly",
//     role: "Chief Technical Officer, Techtitans",
//     location: "Houston, Texas",
//     employees: "11-50 Employees",
//     review:
//       "They consistently met milestones on time and adhered to the agreed-upon timeline.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/331647",

//   },
//   {
//     id: 10,
//     projectSummary: "Web Inventix designed and developed a mobile app for a kitchen remodeling company. The team planned the project, created the UI/UX, developed the app, integrated the backend, tested, and optimized it.",
//     projectService: "Mobile App Development UX/UI Design",
//     prjectSize: "$10,000 to $49,999",
//     projectLenght: "Apr. 2026 - Ongoing",
//     name: "Rhond Dean",
//     role: "Owner, Safeway",
//     location: "Long Beach, California",
//     employees: "11-50 Employees",
//     review:
//       "Their creative suggestions, technical knowledge, and attention to detail added value throughout the project.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/462237",

//   },
//   {
//     id: 11,
//     projectSummary: "Web Inventix provided game development and design staff augmentation for a mobile app development company. The team was responsible for expanding the client's capabilities to build a game using Unity.",
//     projectService: "IT Staff Augmentation Mobile App Development UX/UI Design",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Apr. - May 2026",
//     name: "George Tixi",
//     role: "Team Lead Development, E8 Labs",
//     location: "San Jose, California",
//     employees: "11-50 Employees",
//     review:
//       "What impressed us most was their communication and dedication to delivering quality work.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/461213",

//   },
//   {
//     id: 12,
//     projectSummary: "Web Inventix provided PPC and social media marketing services for a grocery store. The team was responsible for managing the client's social media accounts, creating content, and running PPC campaigns.",
//     projectService: "Pay Per Click, Social Media Marketing",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Oct. 2025 - Jan. 2026",
//     name: "Rhond Dean",
//     role: "Owner, Safeway",
//     location: "Boulder, Colorado",
//     employees: "11-50 Employees",
//     review:
//       "The project was managed professionally with regular communication and weekly progress updates.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/459713",

//   },
//   {
//     id: 13,
//     projectSummary: "Web Inventix developed a mobile application for a cosmetics company. The app was designed to help the client launch their products and reach a wider audience.",
//     projectService: "Mobile App Development",
//     prjectSize: "$10,000 to $49,999",
//     projectLenght: "Dec. 2025 - Apr. 2026",
//     name: "Robert Sharp",
//     role: "Manager, Happy Beauty Co",
//     location: "Tempe, Arizona",
//     employees: "11-50 Employees",
//     review: "They have qualified and experienced developers.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/458946",

//   },
//   {
//     id: 14,
//     projectSummary: "Web Inventix updated and redesigned a web app for a fashion boutique to make it more user-friendly. The team was responsible for collaborating with the client to implement the requested changes.",
//     projectService: "Web Design Web Development",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Feb. - May 2026",
//     name: "Gary Vermillion",
//     role: "Head of Marketing, Razzle Dazzle",
//     location: "Cape Coral, Florida",
//     employees: "11-50 Employees",
//     review:
//       "I knew my project was in safe hands because the project manager was always on time with current updates.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/457956",

//   },
//   {
//     id: 15,
//     projectSummary: "Web Inventix developed a blockchain application for a computer hardware store. The team used C++, Python, and JavaScript as their main coding tools and targeted the Ethereum Virtual Machine.",
//     projectService: "Blockchain",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Jan. - Apr. 2026",
//     name: "Alex Hale",
//     role: "Owner, Northwest Computers",
//     location: "Portland, Oregon",
//     employees: "11-50 Employees",
//     review:
//       "They were timely and competent, and they provided us with timely work.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/453024",

//   },
//   {
//     id: 16,
//     projectSummary: "Web Inventix designed and developed a custom website for a furniture company. They integrated a product catalog, ensured mobile responsiveness, and optimized the platform's performance.",
//     projectService: "Web Design Web Development",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Feb. - Mar. 2026",
//     name: "Dolores Gonzales",
//     role: "CMO, Logan Furniture",
//     location: "Boston, Massachusetts",
//     employees: "11-50 Employees",
//     review: "They managed the project in a timely and organized way.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/445481",

//   },
//   {
//     id: 17,
//     projectSummary: "Web Inventix provided UX/UI design and development services for a gaming company. The team created an interactive interface with a responsive layout, built app and website prototypes, and more.",
//     projectService: "UX/UI Design",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Dec. 2025 - Feb. 2026",
//     name: "Laura Phelps",
//     role: "Operations Director, East Coast Gaming",
//     location: "Milton, Massachusetts",
//     employees: "11-50 Employees",
//     review:
//       "The team managed tasks efficiently, delivered on schedule, and responded quickly to feedback or change requests.",
//     rating: 4.5,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/442680",

//   },
//   {
//     id: 18,
//     projectSummary: "Web Inventix provided website development and SMM for a janitorial services company. The team designed the site, set up accounts, created content, managed campaigns, and implemented lead generation strategies.",
//     projectService: "Social Media Marketing Web Development",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Oct. 2025 - Mar. 2026",
//     name: "Jennifer Owens",
//     role: "Logistics Manager, Bluestar Janitorial",
//     location: "Dallas, Texas",
//     employees: "11-50 Employees",
//     review: "Their ability to understand our service business stood out.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/442433",

//   },
//   {
//     id: 19,
//     projectSummary: "Web Inventix developed an Android app for a real estate company. The app featured property listings, search filters, appointment scheduling, notifications, user authentication, and a backend dashboard.",
//     projectService: "Mobile App Development",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Jan. - Mar. 2026",
//     name: "Austin Willoughby",
//     role: "CMO, Brick & Banister Real Estate Co.",
//     location: "Taylors Falls, Minnesota",
//     employees: "11-50 Employees",
//     review: "They offered creative solutions tailored to our business needs.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/442065",

//   },
//   {
//     id: 20,
//     projectSummary: "Web Inventix built a mobile app for an AI-powered dating app provider. They designed the app, set up cloud infrastructure, and implemented real-time chat and video calls and AI-powered matchmaking features.",
//     projectService: "Mobile App Development UX/UI Design",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Nov. 2024 - Feb. 2025",
//     name: "Nancy Quick",
//     role: "Owner, AI-Powered Dating App Provider",
//     location: "Austin, Texas",
//     employees: "1-10 Employees",
//     review:
//       "They impressed us with their advanced AI technology, smooth UI/UX design, and strong commitment to innovation.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 5.0,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/360389",

//   },
//   {
//     id: 21,
//     projectSummary: "Web Inventix developed a dating app for a dating app provider. The team designed the UI/UX, implemented AI-driven matchmaking technology, and implemented security measures.",
//     projectService: "Mobile App Development UX/UI Design",
//     prjectSize: "$10,000 to $49,999",
//     projectLenght: "May - Oct. 2024",
//     name: "Joesph Barron",
//     role: "Owner, Arts, entertainment & music",
//     location: "San Francisco, California",
//     employees: "1-10 Employees",
//     review:
//       "Their professionalism, responsiveness, and commitment to delivering on time made the process seamless and stress-free.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 4.5,
//     cost: 4.5,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/359146",

//   },
//   {
//     id: 22,
//     projectSummary: "Web Inventix LLC designed and developed a website for an animation company. The team also provided SEO and SMM services to improve the client's engagement, brand exposure, traffic, and leads.",
//     projectService: "Search Engine Optimization Social Media Marketing Web Development",
//     prjectSize: "Less than $10,000",
//     projectLenght: "Feb. - Sep. 2024",
//     name: "Lang Morris",
//     location: "flugerville, Texas",
//     employees: "11-50 Employees",
//     role: "VP, Animation Company",
//     review:
//       "They provide unique solutions that meet or exceed your expectations.",
//     rating: 5.0,
//     quailty: 5.0,
//     schedule: 5.0,
//     cost: 4.5,
//     willingToRefer: 5.0,
//     link: "https://clutch.co/go-to-review/b5db340a-e12f-42e9-aa75-34dc26aff642/332519",

//   },
// ];